#ifndef FLUIR_COMPILER_UTILITY_MACROS_HPP
#define FLUIR_COMPILER_UTILITY_MACROS_HPP

#define FLUIR_CONCAT_IMPL(a, b) a##b
#define FLUIR_CONCAT(a, b) FLUIR_CONCAT_IMPL(a, b)
#define FLUIR_ANONYMOUS_VARIABLE(BaseName) FLUIR_CONCAT(BaseName, __LINE__)

#endif
