# THIS FILE WAS AUTOGENERATED BY CMAKE. DO NOT EDIT IT BY HAND AS CHANGES HERE WILL BE OVERWRITTEN.
# ruff: noqa

from typing import Final

from pydantic.dataclasses import dataclass


@dataclass
class Version:
    MAJOR: int
    MINOR: int
    PATCH: int


FLUIR_CURRENT_VERSION: Final = Version(
    MAJOR=0,
    MINOR=4,
    PATCH=0,
)
