#include <cmath>
#include <tuple>

#include <gtest/gtest.h>

#include "vm/machine/vm.hpp"

using std::tuple;

namespace fc = fluir::code;
using enum fluir::code::Instruction;
using namespace fluir::code::value_literals;

class TestPrimitiveOps : public ::testing::TestWithParam<tuple<fc::Value, fc::ByteCode>> { };

TEST_P(TestPrimitiveOps, Test) {
  auto [expected, code] = GetParam();
  // Add postamble to bytecode to make it execute correctly without requiring too much boilerplate in tests
  code.chunks[0].code.push_back(EXIT);

  fluir::VirtualMachine vm;
  EXPECT_EQ(fluir::ExecResult::SUCCESS, vm.execute(&code));
  auto actual = vm.viewStack().back();
  if (actual.type() == fc::PrimitiveType::F64) {
    // stupid double epsilon issues
    EXPECT_DOUBLE_EQ(expected.asF64(), actual.asF64());
  } else {
    EXPECT_EQ(expected, actual);
  }
}

INSTANTIATE_TEST_SUITE_P(
  Float,
  TestPrimitiveOps,
  ::testing::Values(
    // F64 basic ops
    tuple{3.5_f64,
          fc::ByteCode{.constants = {1.5_f64, 2.0_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_ADD}}}}},
    tuple{1.25_f64,
          fc::ByteCode{.constants = {1.5_f64, 0.25_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_SUB}}}}},
    tuple{12.0_f64,
          fc::ByteCode{.constants = {1.5_f64, 8.0_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_MUL}}}}},
    tuple{0.75_f64,
          fc::ByteCode{.constants = {3.0_f64, 4.0_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}}},
    tuple{4.0_f64,
          fc::ByteCode{.constants = {3.0_f64}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, F64_INC}}}}},
    tuple{2.0_f64,
          fc::ByteCode{.constants = {3.0_f64}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, F64_DEC}}}}},

    // F64 edge cases
    tuple{fc::Value{INFINITY},
          fc::ByteCode{.constants = {1.0e200_f64, 2.0e200_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_MUL}}}}},
    tuple{fc::Value{INFINITY},
          fc::ByteCode{.constants = {3.0_f64, 0.0_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}}},
    tuple{fc::Value{-INFINITY},
          fc::ByteCode{.constants = {fc::Value{-3.0}, 0.0_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}}},
    tuple{fc::Value{INFINITY},
          fc::ByteCode{.constants = {1.0e308_f64, 1.0e308_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_ADD}}}}},
    tuple{fc::Value{-INFINITY},
          fc::ByteCode{.constants = {fc::Value{-1.0e308}, 1.0e308_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_SUB}}}}},
    tuple{0.0_f64,
          fc::ByteCode{.constants = {0.0_f64, 1000.0_f64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_MUL}}}}},
    tuple{fc::Value{-5.5},
          fc::ByteCode{.constants = {fc::Value{-2.5}, fc::Value{-3.0}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_ADD}}}}},
    tuple{2.5_f64,
          fc::ByteCode{.constants = {fc::Value{-2.5}, fc::Value{-5.0}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_SUB}}}}},
    tuple{15.0_f64,
          fc::ByteCode{.constants = {fc::Value{-3.0}, fc::Value{-5.0}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_MUL}}}}},
    tuple{fc::Value{-2.0},
          fc::ByteCode{.constants = {10.0_f64, fc::Value{-5.0}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}}}));

INSTANTIATE_TEST_SUITE_P(
  I8,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{5_i8,
          fc::ByteCode{.constants = {2_i8, 3_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{10_i8,
          fc::ByteCode{.constants = {15_i8, 5_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{20_i8,
          fc::ByteCode{.constants = {4_i8, 5_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{3_i8,
          fc::ByteCode{.constants = {15_i8, 5_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{6_i8, fc::ByteCode{.constants = {5_i8}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_INC}}}}},
    tuple{4_i8, fc::ByteCode{.constants = {5_i8}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_DEC}}}}},
    tuple{fc::Value{static_cast<int8_t>(-5)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-2)}, fc::Value{static_cast<int8_t>(-3)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{5_i8,
          fc::ByteCode{.constants = {10_i8, fc::Value{static_cast<int8_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{fc::Value{(int8_t)-15},
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-10)}, 5_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{(int8_t)-20},
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-4)}, 5_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{20_i8,
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-4)}, fc::Value{static_cast<int8_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{fc::Value{(int8_t)-3},
          fc::ByteCode{.constants = {15_i8, fc::Value{static_cast<int8_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{fc::Value{(int8_t)-3},
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-15)}, 5_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{3_i8,
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-15)}, fc::Value{static_cast<int8_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{static_cast<int8_t>(-128),
          fc::ByteCode{.constants = {127_i8, 1_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{127_i8,
          fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-128)}, 1_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{static_cast<int8_t>(-2)},
          fc::ByteCode{.constants = {127_i8, 2_i8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}}));
INSTANTIATE_TEST_SUITE_P(
  I16,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{500_i16,
          fc::ByteCode{.constants = {200_i16, 300_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{1000_i16,
          fc::ByteCode{.constants = {1500_i16, 500_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{2000_i16,
          fc::ByteCode{.constants = {40_i16, 50_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{30_i16,
          fc::ByteCode{.constants = {150_i16, 5_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{6_i16, fc::ByteCode{.constants = {5_i16}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_INC}}}}},
    tuple{4_i16, fc::ByteCode{.constants = {5_i16}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_DEC}}}}},
    tuple{fc::Value{static_cast<int16_t>(-500)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-200)}, fc::Value{static_cast<int16_t>(-300)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{500_i16,
          fc::ByteCode{.constants = {1000_i16, fc::Value{static_cast<int16_t>(-500)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{fc::Value{static_cast<int16_t>(-1500)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-1000)}, 500_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{static_cast<int16_t>(-2000)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-40)}, 50_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{2000_i16,
          fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-40)}, fc::Value{static_cast<int16_t>(-50)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{fc::Value{static_cast<int16_t>(-30)},
          fc::ByteCode{.constants = {150_i16, fc::Value{static_cast<int16_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{static_cast<int16_t>(-32768),
          fc::ByteCode{.constants = {32767_i16, 1_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{32767_i16,
          fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-32768)}, 1_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{static_cast<int16_t>(-2)},
          fc::ByteCode{.constants = {32767_i16, 2_i16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}}));
INSTANTIATE_TEST_SUITE_P(
  I32,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{50000_i32,
          fc::ByteCode{.constants = {20000_i32, 30000_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{100000_i32,
          fc::ByteCode{.constants = {150000_i32, 50000_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{200000_i32,
          fc::ByteCode{.constants = {4000_i32, 50_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{3000_i32,
          fc::ByteCode{.constants = {15000_i32, 5_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{243_i32,
          fc::ByteCode{.constants = {242_i32}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_INC}}}}},
    tuple{241_i32,
          fc::ByteCode{.constants = {242_i32}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_DEC}}}}},
    tuple{fc::Value{static_cast<int32_t>(-50000)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-20000)}, fc::Value{static_cast<int32_t>(-30000)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{50000_i32,
          fc::ByteCode{.constants = {100000_i32, fc::Value{static_cast<int32_t>(-50000)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{fc::Value{static_cast<int32_t>(-150000)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-100000)}, 50000_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{static_cast<int32_t>(-200000)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-4000)}, 50_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{200000_i32,
          fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-4000)}, fc::Value{static_cast<int32_t>(-50)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{fc::Value{static_cast<int32_t>(-3000)},
          fc::ByteCode{.constants = {15000_i32, fc::Value{static_cast<int32_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{static_cast<int32_t>(-2147483648),
          fc::ByteCode{.constants = {2147483647_i32, 1_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{2147483647_i32,
          fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-2147483648)}, 1_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{static_cast<int32_t>(-2)},
          fc::ByteCode{.constants = {2147483647_i32, 2_i32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}}));
INSTANTIATE_TEST_SUITE_P(
  I64,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{5000000000_i64,
          fc::ByteCode{.constants = {2000000000_i64, 3000000000_i64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{10000000000_i64,
          fc::ByteCode{.constants = {15000000000_i64, 5000000000_i64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{20000000000_i64,
          fc::ByteCode{.constants = {4000000_i64, 5000_i64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{3000000_i64,
          fc::ByteCode{.constants = {15000000_i64, 5_i64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}},
    tuple{6_i64, fc::ByteCode{.constants = {5_i64}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_INC}}}}},
    tuple{4_i64, fc::ByteCode{.constants = {5_i64}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, I64_DEC}}}}},
    tuple{fc::Value{static_cast<int64_t>(-5000000000)},
          fc::ByteCode{
            .constants = {fc::Value{static_cast<int64_t>(-2000000000)}, fc::Value{static_cast<int64_t>(-3000000000)}},
            .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{5000000000_i64,
          fc::ByteCode{.constants = {10000000000_i64, fc::Value{static_cast<int64_t>(-5000000000)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}}}}},
    tuple{fc::Value{static_cast<int64_t>(-15000000000)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int64_t>(-10000000000)}, 5000000000_i64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB}}}}},
    tuple{fc::Value{static_cast<int64_t>(-20000000000)},
          fc::ByteCode{.constants = {fc::Value{static_cast<int64_t>(-4000000)}, 5000_i64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{20000000000_i64,
          fc::ByteCode{.constants = {fc::Value{static_cast<int64_t>(-4000000)}, fc::Value{static_cast<int64_t>(-5000)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}}}}},
    tuple{fc::Value{static_cast<int64_t>(-3000000)},
          fc::ByteCode{.constants = {15000000_i64, fc::Value{static_cast<int64_t>(-5)}},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}}
    // TODO: Figure out how to handle i64 overflow gracefully
    // tuple{static_cast<int64_t>(-9223372036854775807LL - 1),
    //       fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_ADD}, .constants = {9223372036854775807_i64,
    //       1_i64}}},
    // tuple{9223372036854775807_i64,
    //       fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_SUB},
    //                 .constants = {fc::Value{static_cast<int64_t>(-9223372036854775807LL - 1)}, 1_i64}}},
    // tuple{fc::Value{static_cast<int64_t>(-2)},
    //       fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_MUL}, .constants = {9223372036854775807_i64,
    //       2_i64}}}
    ));

INSTANTIATE_TEST_SUITE_P(
  U8,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{5_u8,
          fc::ByteCode{.constants = {2_u8, 3_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{10_u8,
          fc::ByteCode{.constants = {15_u8, 5_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{20_u8,
          fc::ByteCode{.constants = {4_u8, 5_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{3_u8,
          fc::ByteCode{.constants = {15_u8, 5_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{100_u8,
          fc::ByteCode{.constants = {100_u8, 0_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{50_u8,
          fc::ByteCode{.constants = {50_u8, 0_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{0_u8,
          fc::ByteCode{.constants = {100_u8, 0_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{0_u8,
          fc::ByteCode{.constants = {0_u8, 100_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{3_u8,
          fc::ByteCode{.constants = {10_u8, 3_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{5_u8,
          fc::ByteCode{.constants = {17_u8, 3_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{0_u8,
          fc::ByteCode{.constants = {255_u8, 1_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{1_u8,
          fc::ByteCode{.constants = {255_u8, 2_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{10_u8,
          fc::ByteCode{.constants = {255_u8, 11_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{12_u8, fc::ByteCode{.constants = {11_u8}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_INC}}}}},
    tuple{10_u8, fc::ByteCode{.constants = {11_u8}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_DEC}}}}},
    tuple{fc::Value{static_cast<uint8_t>(254)},
          fc::ByteCode{.constants = {255_u8, 2_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{fc::Value{static_cast<uint8_t>(255)},
          fc::ByteCode{.constants = {0_u8, 1_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint8_t>(251)},
          fc::ByteCode{.constants = {5_u8, 10_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint8_t>(245)},
          fc::ByteCode{.constants = {0_u8, 11_u8},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}}));
INSTANTIATE_TEST_SUITE_P(
  U16,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{500_u16,
          fc::ByteCode{.constants = {200_u16, 300_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{1000_u16,
          fc::ByteCode{.constants = {1500_u16, 500_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{2000_u16,
          fc::ByteCode{.constants = {40_u16, 50_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{30_u16,
          fc::ByteCode{.constants = {150_u16, 5_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{10000_u16,
          fc::ByteCode{.constants = {10000_u16, 0_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{5000_u16,
          fc::ByteCode{.constants = {5000_u16, 0_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{0_u16,
          fc::ByteCode{.constants = {10000_u16, 0_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{0_u16,
          fc::ByteCode{.constants = {0_u16, 10000_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{333_u16,
          fc::ByteCode{.constants = {1000_u16, 3_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{566_u16,
          fc::ByteCode{.constants = {1700_u16, 3_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{0_u16,
          fc::ByteCode{.constants = {65535_u16, 1_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{10_u16,
          fc::ByteCode{.constants = {65535_u16, 11_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{345_u16,
          fc::ByteCode{.constants = {344_u16}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_INC}}}}},
    tuple{343_u16,
          fc::ByteCode{.constants = {344_u16}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_DEC}}}}},
    tuple{fc::Value{static_cast<uint16_t>(65534)},
          fc::ByteCode{.constants = {65535_u16, 2_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{fc::Value{static_cast<uint16_t>(65535)},
          fc::ByteCode{.constants = {0_u16, 1_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint16_t>(65531)},
          fc::ByteCode{.constants = {5_u16, 10_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint16_t>(65525)},
          fc::ByteCode{.constants = {0_u16, 11_u16},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}}));
INSTANTIATE_TEST_SUITE_P(
  U32,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{50000_u32,
          fc::ByteCode{.constants = {20000_u32, 30000_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{100000_u32,
          fc::ByteCode{.constants = {150000_u32, 50000_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{200000_u32,
          fc::ByteCode{.constants = {4000_u32, 50_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{3000_u32,
          fc::ByteCode{.constants = {15000_u32, 5_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{1000000_u32,
          fc::ByteCode{.constants = {1000000_u32, 0_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{500000_u32,
          fc::ByteCode{.constants = {500000_u32, 0_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{0_u32,
          fc::ByteCode{.constants = {1000000_u32, 0_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{0_u32,
          fc::ByteCode{.constants = {0_u32, 1000000_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{33333_u32,
          fc::ByteCode{.constants = {100000_u32, 3_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{56666_u32,
          fc::ByteCode{.constants = {170000_u32, 3_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{0_u32,
          fc::ByteCode{.constants = {4294967295_u32, 1_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{10_u32,
          fc::ByteCode{.constants = {4294967295_u32, 11_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{12_u32,
          fc::ByteCode{.constants = {11_u32}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_INC}}}}},
    tuple{10_u32,
          fc::ByteCode{.constants = {11_u32}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_DEC}}}}},
    tuple{fc::Value{static_cast<uint32_t>(4294967294)},
          fc::ByteCode{.constants = {4294967295_u32, 2_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{fc::Value{static_cast<uint32_t>(4294967295)},
          fc::ByteCode{.constants = {0_u32, 1_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint32_t>(4294967291)},
          fc::ByteCode{.constants = {5_u32, 10_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint32_t>(4294967285)},
          fc::ByteCode{.constants = {0_u32, 11_u32},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}}));
INSTANTIATE_TEST_SUITE_P(
  U64,
  TestPrimitiveOps,
  ::testing::Values(
    tuple{5000000000_u64,
          fc::ByteCode{.constants = {2000000000_u64, 3000000000_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{10000000000_u64,
          fc::ByteCode{.constants = {15000000000_u64, 5000000000_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{20000000000_u64,
          fc::ByteCode{.constants = {4000000_u64, 5000_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{3000000_u64,
          fc::ByteCode{.constants = {15000000_u64, 5_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{10000000000_u64,
          fc::ByteCode{.constants = {10000000000_u64, 0_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{5000000000_u64,
          fc::ByteCode{.constants = {5000000000_u64, 0_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{0_u64,
          fc::ByteCode{.constants = {10000000000_u64, 0_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{0_u64,
          fc::ByteCode{.constants = {0_u64, 10000000000_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{3333333333_u64,
          fc::ByteCode{.constants = {10000000000_u64, 3_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{5666666666_u64,
          fc::ByteCode{.constants = {17000000000_u64, 3_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}},
    tuple{0_u64,
          fc::ByteCode{.constants = {18446744073709551615_u64, 1_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{10_u64,
          fc::ByteCode{.constants = {18446744073709551615_u64, 11_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_ADD}}}}},
    tuple{1112_u64,
          fc::ByteCode{.constants = {1111_u64}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_INC}}}}},
    tuple{1110_u64,
          fc::ByteCode{.constants = {1111_u64}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, U64_DEC}}}}},
    tuple{fc::Value{static_cast<uint64_t>(18446744073709551614ULL)},
          fc::ByteCode{.constants = {18446744073709551615_u64, 2_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_MUL}}}}},
    tuple{fc::Value{static_cast<uint64_t>(18446744073709551615ULL)},
          fc::ByteCode{.constants = {0_u64, 1_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint64_t>(18446744073709551611ULL)},
          fc::ByteCode{.constants = {5_u64, 10_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}},
    tuple{fc::Value{static_cast<uint64_t>(18446744073709551605ULL)},
          fc::ByteCode{.constants = {0_u64, 11_u64},
                       .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_SUB}}}}}));

// Test this separately since NAN isn't equal to NAN
class TestPrimitiveOpsProducingNans : public ::testing::TestWithParam<fc::ByteCode> { };
TEST_P(TestPrimitiveOpsProducingNans, Test0Div) {
  auto code = GetParam();
  code.chunks[0].code.push_back(EXIT);
  // With NANs, compare slightly differently

  fluir::VirtualMachine vm;
  EXPECT_EQ(fluir::ExecResult::SUCCESS, vm.execute(&code));
  auto actual = vm.viewStack().back();
  EXPECT_TRUE(std::isnan(actual.asF64()));
}

static const auto NAN_FL_VALUE = fc::Value{NAN};

INSTANTIATE_TEST_SUITE_P(
  TestPrimitiveOpsProducingNans,
  TestPrimitiveOpsProducingNans,
  ::testing::Values(
    fc::ByteCode{.constants = {0.0_f64, 0.0_f64},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}},
    fc::ByteCode{.constants = {1.0_f64, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_ADD}}}},
    fc::ByteCode{.constants = {2.0_f64, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_SUB}}}},
    fc::ByteCode{.constants = {5.0_f64, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_MUL}}}},
    fc::ByteCode{.constants = {3.0_f64, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}},
    fc::ByteCode{.constants = {NAN_FL_VALUE, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_ADD}}}},
    fc::ByteCode{.constants = {NAN_FL_VALUE, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_SUB}}}},
    fc::ByteCode{.constants = {NAN_FL_VALUE, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_MUL}}}},
    fc::ByteCode{.constants = {NAN_FL_VALUE, NAN_FL_VALUE},
                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, F64_DIV}}}},
    fc::ByteCode{.constants = {NAN_FL_VALUE}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, F64_NEG}}}},
    fc::ByteCode{.constants = {NAN_FL_VALUE}, .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, F64_AFF}}}}));

class TestDivideByZeroCrashes : public ::testing::TestWithParam<fc::ByteCode> { };
TEST_P(TestDivideByZeroCrashes, Test) {
  auto code = GetParam();
  code.chunks[0].code.push_back(EXIT);

  fluir::VirtualMachine vm;
  EXPECT_EQ(fluir::ExecResult::ERROR_DIVIDE_BY_ZERO, vm.execute(&code));
}

INSTANTIATE_TEST_SUITE_P(
  I8,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {10_i8, 0_i8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-10)}, 0_i8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {0_i8, 0_i8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {127_i8, 0_i8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int8_t>(-128)}, 0_i8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  I16,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {1000_i16, 0_i16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-1000)}, 0_i16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {0_i16, 0_i16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {32767_i16, 0_i16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int16_t>(-32768)}, 0_i16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  I32,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {100000_i32, 0_i32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-100000)}, 0_i32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {0_i32, 0_i32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {2147483647_i32, 0_i32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int32_t>(-2147483648)}, 0_i32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  I64,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {1000000000_i64, 0_i64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int64_t>(-1000000000)}, 0_i64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {0_i64, 0_i64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {9223372036854775807_i64, 0_i64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}},
                    fc::ByteCode{.constants = {fc::Value{static_cast<int64_t>(-9223372036854775807LL - 1)}, 0_i64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, I64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  U8,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {10_u8, 0_u8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {0_u8, 0_u8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {255_u8, 0_u8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {128_u8, 0_u8},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  U16,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {1000_u16, 0_u16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {0_u16, 0_u16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {65535_u16, 0_u16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {32768_u16, 0_u16},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  U32,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {100000_u32, 0_u32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {0_u32, 0_u32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {4294967295_u32, 0_u32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {2147483648_u32, 0_u32},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}));
INSTANTIATE_TEST_SUITE_P(
  U64,
  TestDivideByZeroCrashes,
  ::testing::Values(fc::ByteCode{.constants = {1000000000_u64, 0_u64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {0_u64, 0_u64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {18446744073709551615_u64, 0_u64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}},
                    fc::ByteCode{.constants = {9223372036854775808_u64, 0_u64},
                                 .chunks = {fc::Chunk{.name = "main", .code = {PUSH, 0, PUSH, 1, U64_DIV}}}}));
