function (create_version_files)
    set(AUTOGENERATED_WARNING
        "THIS FILE WAS AUTOGENERATED BY CMAKE. DO NOT EDIT IT BY HAND AS CHANGES HERE WILL BE OVERWRITTEN."
    )

    # Create editor version file
    set(EDITOR_DIRECTORY ${CMAKE_SOURCE_DIR}/editor/server)

    configure_file(
        "${EDITOR_DIRECTORY}/editor/models/version.py.in"
        "${EDITOR_DIRECTORY}/editor/models/version.py"
        USE_SOURCE_PERMISSIONS
    )

    # TODO: Create compiler version file

    # TODO: Create VM version file

endfunction ()
