function (create_version_files)
    set(AUTOGENERATED_WARNING
        "THIS FILE WAS AUTOGENERATED BY CMAKE. DO NOT EDIT IT BY HAND AS CHANGES HERE WILL BE OVERWRITTEN."
    )

    # Create editor version file
    set(EDITOR_DIRECTORY ${CMAKE_SOURCE_DIR}/editor/server)

    configure_file(
        "${EDITOR_DIRECTORY}/editor/models/version.py.in"
        "${EDITOR_DIRECTORY}/editor/models/version.py"
        USE_SOURCE_PERMISSIONS
    )

    # Create language version file
    set(BYTECODE_DIRECTORY ${CMAKE_SOURCE_DIR}/bytecode)
    configure_file(
        "${BYTECODE_DIRECTORY}/include/bytecode/version.hpp.in"
        "${BYTECODE_DIRECTORY}/include/bytecode/version.hpp"
        USE_SOURCE_PERMISSIONS
    )

endfunction ()
